FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY modules/SampleModule/*.csproj ./
RUN dotnet restore

COPY modules/SampleModule/ ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime-nanoserver-1803
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "SampleModule.dll"]